name: tbib_timezone_offset
description: This Package used for Get date time with offset to local time ,
  format time or convert it to iso format with date phone without location and
  server time zone.
version: 0.0.2

homepage: "https://github.com/the-best-is-best/tbib_timezone_offset"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0
